### ISSUE TITLE
ERROR neqsim.thermo.phase.PhaseEos - Failed to solve for molarVolume within the iteration limit

### ISSUE THREAD

**Issue by maksymmoroz11** [equinor/neqsim-python#269]
Hello!

I have similar issue that has been mentioned in #241 and #267 and I haven't components with mole fraction 0.
I have used code from [example](https://github.com/EvenSol/NeqSim-Colab/blob/0500935cc84857432c27ecbbe7ab237726771bb3/notebooks/gasquality/hydrocarbon_dew_point_of_natural_gas.ipynb) but have written my gas composition from the real task:

```
import neqsim
from neqsim.neqsimpython import jNeqSim
from neqsim.thermo.thermoTools import *
import matplotlib.pyplot as plt


fluid0_HC = fluid('umr')
fluid0_HC.addComponent('nitrogen',2.5)
fluid0_HC.addComponent('CO2',4.5)
fluid0_HC.addComponent('methane',79.45)
fluid0_HC.addComponent('ethane',10)
fluid0_HC.addComponent('propane',2.5)
fluid0_HC.addComponent('i-butane',0.3)
fluid0_HC.addComponent('n-butane',0.5)
fluid0_HC.addComponent('22-dim-C3',0.01)
fluid0_HC.addComponent('i-pentane',0.05)
fluid0_HC.addComponent('n-pentane',0.05)
fluid0_HC.addComponent('n-hexane',0.05)
fluid0_HC.addComponent('benzene',0.02)
fluid0_HC.addComponent('c-hexane',0.02)
fluid0_HC.addComponent('n-heptane',0.02)
fluid0_HC.addComponent('toluene',0.01)
fluid0_HC.addComponent('n-octane',0.01)
fluid0_HC.setMixingRule("HV", "UNIFAC_UMRPRU")
thermoOps = jNeqSim.thermodynamicOperations.ThermodynamicOperations(fluid0_HC)
thermoOps.calcPTphaseEnvelope()

plt.plot(list(thermoOps.getOperation().get("dewT")),list(thermoOps.getOperation().get("dewP")), label="dew point")
plt.plot(list(thermoOps.getOperation().get("bubT")),list(thermoOps.getOperation().get("bubP")), label="bubble point")
plt.title('PT envelope')
plt.xlabel('Temperature [K]')
plt.ylabel('Pressure [bar]')
plt.legend()
plt.show()
```

When I tried to get PT envelope with exactly code I showed above with toluene in mixture I met an eror:
`[main] ERROR neqsim.thermo.phase.PhaseEos - Failed to solve for molarVolume within the iteration limit.`
and get obviously wrong PT envelope:
![изображение](https://github.com/equinor/neqsim-python/assets/62216211/fe9ea225-5ef8-46fc-af73-4b3a00845bf7).

But when I commented string with toluene adding, I didn't met any errors and got correct PT envelope:
![изображение](https://github.com/equinor/neqsim-python/assets/62216211/beac01c2-8ae3-4ea3-9a00-1ae30e20b59b)

I also met this error earlier with different gas composition and when I will reproduce it, I can send that code. 
Could you please explain what is the root of this error and could you give limitations of gas composition NeqSim have, if they exist?

**Comment by maksymmoroz11** [comment]
Hello!

Today I again got this error when I tried to got PT envelope with gas composition given above without toluene but with 0.03 % of n-octane instead of 0.01 %:
```
import neqsim
from neqsim.neqsimpython import jNeqSim
from neqsim.thermo.thermoTools import *
import matplotlib.pyplot as plt

fluid0_HC = fluid('umr')
fluid0_HC.addComponent('methane', 79.45)
fluid0_HC.addComponent('ethane', 10)
fluid0_HC.addComponent('propane', 2.5)
fluid0_HC.addComponent('i-butane', 0.3)
fluid0_HC.addComponent('n-butane', 0.5)
fluid0_HC.addComponent('i-pentane', 0.05)
fluid0_HC.addComponent('n-pentane', 0.05)
fluid0_HC.addComponent('22-dim-C3', 0.01)
fluid0_HC.addComponent('benzene', 0.02)
fluid0_HC.addComponent('c-hexane', 0.02)
fluid0_HC.addComponent('n-hexane', 0.05)
fluid0_HC.addComponent('n-heptane', 0.02)
fluid0_HC.addComponent('n-octane', 0.03)
fluid0_HC.addComponent('nitrogen', 2.5)
fluid0_HC.addComponent('CO2', 4.5)
fluid0_HC.setMixingRule("HV", "UNIFAC_UMRPRU")

thermoOps = jNeqSim.thermodynamicOperations.ThermodynamicOperations(fluid0_HC)
thermoOps.calcPTphaseEnvelope()

plt.plot(list(thermoOps.getOperation().get("dewT"))[:30],list(thermoOps.getOperation().get("dewP"))[:30], label="dew point")
plt.title('PT envelope')
plt.xlabel('Temperature [K]')
plt.ylabel('Pressure [bar]')
plt.legend()
plt.show()
```

**Comment by EvenSol** [comment]
I will look into it. 

It seems like getting the data using the following code will help:
plt.plot(list(thermoOps.getOperation().get("dewT2")),list(thermoOps.getOperation().get("dewP2")), label="dew point")
plt.plot(list(thermoOps.getOperation().get("bubT2")),list(thermoOps.getOperation().get("bubP2")), label="bubble point")

But this should be updated in a future version (so we dont have to check for data in more than one way).

**Comment by EvenSol** [comment]
We have implemented a new version of collecting the data. Can you try the folloing method, and see if that helps?

thermoOps.calcPTphaseEnvelope2()
plt.plot(list(thermoOps.getOperation().get("dewT")), list(thermoOps.getOperation().get("dewP")), label="DewPoint")
plt.plot(list(thermoOps.getOperation().get("bubT")), list(thermoOps.getOperation().get("bubP")), label="BubblePoint")

I have tested your fluid in this notebook, and it seems to work. Howeer still some issues around the critical point.
https://colab.research.google.com/drive/1tuSXN5Myk97SSxxJJ21vo4G8lwILT9K2#scrollTo=Dlr7mSMA07b3

**Comment by EvenSol** [comment]
If anyone finds time to improve the phase envelope algorithms, they should look into improving the following method in neqsim: I is based on the algorithms of Michelsen (1980) (https://www.sciencedirect.com/science/article/abs/pii/037838128080001X).

https://github.com/equinor/neqsim/blob/master/src/main/java/neqsim/thermodynamicOperations/phaseEnvelopeOps/multicomponentEnvelopeOps/pTphaseEnvelopeNew2.java

and 

https://github.com/equinor/neqsim/blob/master/src/main/java/neqsim/thermodynamicOperations/phaseEnvelopeOps/multicomponentEnvelopeOps/sysNewtonRhapsonPhaseEnvelope.java

**Comment by maksymmoroz11** [comment]
> We have implemented a new version of collecting the data. Can you try the folloing method, and see if that helps?

Hello! 

I already have tested a new version of neqsim library with your code and for now everything works excellent even with so abnormal data, I don't see errors anymore. Thank you very much.

Critical points and bubble point plots I don't use in my in my application and I haven't test it.
