### ISSUE TITLE
Matrix is singular error using C7 component

### ISSUE THREAD

**Issue by torlid** [equinor/neqsim-python#308]
fluid_df gives "Matrix is singular" error using C7. (C6 is ok)

self.gas = fluid_df(gasdf, lastIsPlusFraction=True, autoSetModel=True, modelName='SRK-EOS')

I'am sure this code has been working fine before.

**this df is ok**

  ComponentName MolarComposition[-]  MolarMass[kg/mol]  RelativeDensity[-]
0          water               0.174                NaN                 NaN
1       nitrogen               0.892                NaN                 NaN
2            CO2               1.464                NaN                 NaN
3        methane              77.672                NaN                 NaN
4         ethane               8.283                NaN                 NaN
5        propane               6.038                NaN                 NaN
6       i-butane               2.591                NaN                 NaN
7       n-butane                1.09                NaN                 NaN
8      i-pentane               0.702                NaN                 NaN
9      n-pentane               0.618                NaN                 NaN
14            C6               0.377             0.0862               0.664

**this is not** 

   ComponentName MolarComposition[-]  MolarMass[kg/mol]  RelativeDensity[-]
0          water               0.174                NaN                 NaN
1       nitrogen               0.892                NaN                 NaN
2            CO2               1.464                NaN                 NaN
3        methane              77.672                NaN                 NaN
4         ethane               8.283                NaN                 NaN
5        propane               6.038                NaN                 NaN
6       i-butane               2.591                NaN                 NaN
7       n-butane                1.09                NaN                 NaN
8      i-pentane               0.702                NaN                 NaN
9      n-pentane               0.618                NaN                 NaN
14            C6               0.377             0.0862               0.664
15            C7                 0.1             0.0913               0.746

**Comment by EvenSol** [comment]
Thanks for reporting this issue. I will look into it ASAP.

**Comment by EvenSol** [comment]
Recreated bug:

https://colab.research.google.com/drive/1_twWhwMlx5LylQ2X9RkLZM8Tk3MCDAEF#scrollTo=dVTufcaSJJxc
